In [2]:
from sklearn.datasets import load_digits, load_breast_cancer

In [17]:
from sklearn.model_selection import cross_val_score

In [9]:
import numpy as np

In [11]:
digits=load_digits()
breast_cancer=load_breast_cancer()

In [12]:
X_dig=digits.data
y_dig=digits.target

X_br=breast_cancer.data
y_br=breast_cancer.target

In [35]:
X_dig[2,:]

array([ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
       14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
        1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
        0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  3., 13., 16.,
       16., 11.,  5.,  0.,  0.,  0.,  0.,  3., 11., 16.,  9.,  0.])

In [29]:
y_dig

array([0, 1, 2, ..., 8, 9, 8])

In [39]:
X_br[:,:]<0

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [31]:
y_br

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

**1 вопрос**

In [18]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB 

In [19]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()

In [21]:
print(np.mean(cross_val_score(gnb, X_br,y_br)),
    np.mean(cross_val_score(mnb, X_br,y_br)),
    np.mean(cross_val_score(bnb, X_br,y_br)))

0.9367492806089297 0.8945790401930752 0.6274204028589994


In [24]:
with open('bayes_answer1.txt','w') as f:
    f.write(str(np.mean(cross_val_score(gnb, X_br,y_br))))

**2 вопрос**

In [22]:
print(np.mean(cross_val_score(gnb, X_dig,y_dig)),
    np.mean(cross_val_score(mnb, X_dig,y_dig)),
    np.mean(cross_val_score(bnb, X_dig,y_dig)))

0.8186003803550138 0.8708771489735053 0.8258236507780582


In [25]:
with open('bayes_answer2.txt','w') as f:
    f.write(str(np.mean(cross_val_score(mnb, X_dig,y_dig))))

**3 вопрос**

In [40]:
with open('bayes_answer3.txt','w') as f:
    f.write(str(3)+' '+str(4))